// Stories Configuration
// Generated by Story Configuration Tool

const storiesConfig = {
    "site": {
        "title": "Dwarven Forged Stories",
        "subtitle": "Legends of the Seeds",
        "description": "Explore the mythic tales behind our seed strains, forged in the ancient traditions of the dwarven masters and the secrets of nature's deepest magic.",
        "logoUrl": "https://www.dwarvenforged.com/img/logo.jpg",
        "homeUrl": "https://www.dwarvenforged.com",
        "audioNote": "All stories in the Brokkr Saga are available as audio recordings, bringing these mythic tales to life through sound."
    },
    "collections": {
        "collection1": {
            "id": "collection1",
            "title": "Collection I: The Early Years",
            "description": "Follow the journey of the master craftsman Brokkr, from his legendary beginnings to his greatest creation and lasting legacy.",
            "stories": {
                "story-0005": {
                    "id": "story-0005",
                    "title": "The Forge Wager",
                    "sequence": "Part 1 of Brokkr's Saga",
                    "description": "When Loki cuts off Sif's golden hair, Brokkr is drawn into a dangerous wager that will test his craft against the legendary Sons of Ivaldi. The result: the creation of Mjolnir, the most powerful weapon in the Nine Realms.",
                    "image": "story-0005/ForgeWager.jpg",
                    "displayOrder": 1,
                    "hasAudio": true,
                    "isNew": false,
                    "downloadOptions": [
                        "fantasy",
                        "audio"
                    ]
                },
                "story-0003": {
                    "id": "story-0003",
                    "title": "The Forge Trial",
                    "sequence": "Part 2 of Brokkr's Saga",
                    "description": "Before becoming the legendary craftsman of the Nine Realms, Brokkr must endure imprisonment by the fire giants of Muspelheim. Through cunning, knowledge, and innovation, he transforms his captivity into an opportunity that will change the nature of his craft forever.",
                    "image": "story-0003/ForgeTrial.jpg",
                    "displayOrder": 2,
                    "hasAudio": true,
                    "isNew": false,
                    "downloadOptions": [
                        "fantasy",
                        "audio"
                    ]
                },
                "story-0004": {
                    "id": "story-0004",
                    "title": "The Forge Council",
                    "sequence": "Part 3 of Brokkr's Saga",
                    "description": "After his return from captivity, Brokkr establishes the Forge Council, a community of craftsmen dedicated to the art of seedcraft. Through nine sacred principles, he builds a legacy that will outlast him and shape the future of the Nine Realms.",
                    "image": "story-0004/ForgeCouncil.jpg",
                    "displayOrder": 3,
                    "hasAudio": true,
                    "isNew": false,
                    "downloadOptions": [
                        "fantasy",
                        "audio"
                    ]
                },
                "story-0001": {
                    "id": "story-0001",
                    "title": "The Forge Root Flame",
                    "sequence": "Part 4 of Brokkr's Saga",
                    "description": "When a blight threatens the Nine Realms, master craftsman Brokkr must forge a Seed of Renewal in his legendary anvil deep beneath Svartalfheim. But the price of creation may be higher than even a dwarf can bear.",
                    "image": "story-0001/ForgeRootFlame.jpg",
                    "displayOrder": 4,
                    "hasAudio": true,
                    "isNew": false,
                    "downloadOptions": [
                        "fantasy",
                        "audio"
                    ]
                },
                "story-0002": {
                    "id": "story-0002",
                    "title": "Daughter of the Forge",
                    "sequence": "Part 5 of Brokkr's Saga",
                    "description": "Years after her father's sacrifice, Nostri journeys into the depths of Svartalfheim to find what remains of Brokkr. With unlikely help from Loki, she discovers that the fires of creation never truly die—they only wait to be relit.",
                    "image": "story-0002/ForgeDaughter.jpg",
                    "displayOrder": 5,
                    "hasAudio": true,
                    "isNew": false,
                    "downloadOptions": [
                        "fantasy",
                        "audio"
                    ]
                },
                "story-0006": {
                    "id": "story-0006",
                    "title": "The Forge Journey",
                    "sequence": "Part 6 of Brokkr's Saga",
                    "description": "After his rebirth, Brokkr embarks on a mission to share his craft across the Nine Realms. Teaching others to adapt seedcraft to their own environments, he creates a network of knowledge exchange that transforms not just how seeds grow, but how realms connect.",
                    "image": "story-0006/ForgeJourney.jpg",
                    "displayOrder": 6,
                    "hasAudio": true,
                    "isNew": false,
                    "downloadOptions": [
                        "fantasy",
                        "audio"
                    ]
                },
                "story-0007": {
                    "id": "story-0007",
                    "title": "The Forge Detail",
                    "sequence": "Part 7 of Brokkr's Saga",
                    "description": "While establishing seed exchanges in Alfheim, Brokkr discovers dark elves living in secret. As he learns their mastery of precision and microscopic detail, they in turn discover his knowledge of scaling work across different magnitudes. Together, they create a hidden alliance that bridges realms in unexpected ways.",
                    "image": "story-0007/ForgeDetail.jpg",
                    "displayOrder": 7,
                    "hasAudio": true,
                    "isNew": false,
                    "downloadOptions": [
                        "fantasy",
                        "audio"
                    ]
                },
                "story-0008": {
                    "id": "story-0008",
                    "title": "The Forge Chronicle",
                    "sequence": "Part 8 of Brokkr's Saga",
                    "description": "Brokkr encounters Eddan, a court scribe who abandoned comfort to record tales worth telling. What begins as Brokkr offering aid to a traveler transforms into an unexpected partnership, as Eddan's gift for storytelling helps spread seedcraft knowledge across the realms far beyond what Brokkr could achieve alone.",
                    "image": "story-0008/ForgeChronicle.jpg",
                    "displayOrder": 8,
                    "hasAudio": true,
                    "isNew": false,
                    "downloadOptions": [
                        "fantasy",
                        "audio"
                    ]
                },
                "story-0009": {
                    "id": "story-0009",
                    "title": "The Forge Reunion",
                    "sequence": "Part 9 of Brokkr's Saga",
                    "description": "Brokkr recounts the tale of Lonetree, a towering, tattooed human who once led a fellowship of knowledge-sharers across the realms. Separated by the Great Withering, they reunite decades later to establish Forge Gardens—permanent communities where their different approaches to craft and growth combine to create something greater than either could achieve alone.",
                    "image": "story-0009/ForgeReunion.jpg",
                    "displayOrder": 9,
                    "hasAudio": true,
                    "isNew": false,
                    "downloadOptions": [
                        "fantasy",
                        "audio"
                    ]
                },
                "story-0010": {
                    "id": "story-0010",
                    "title": "The Forge Bond",
                    "sequence": "Part 10 of Brokkr's Saga",
                    "description": "After his imprisonment among the fire giants, Brokkr meets Elri, a seed-tender with Vanir heritage, and her young daughter Nostri. Despite facing a second confinement for forbidden experiments, they build a life combining dwarven metallurgy with plant-craft. When fire destroys their seedforge and years of research, they discover that from the ashes, the most resilient creations emerge—both in their work and in their bond as a family.",
                    "image": "story-0010/ForgeBond.jpg",
                    "displayOrder": 10,
                    "hasAudio": true,
                    "isNew": false,
                    "downloadOptions": [
                        "fantasy",
                        "audio"
                    ]
                },
                "story-0011": {
                    "id": "story-0011",
                    "title": "The Phoenix Flame",
                    "sequence": "Part 11 of Brokkr's Saga",
                    "description": "After the devastating fire, Brokkr and Elri discover that many had preserved fragments of their work. These \"ember carriers\" become the foundation of a special honor—the Phoenix Flame. Recipients are gifted handcrafted wooden boxes containing the rarest seeds, including mysterious \"Lost and Found\" varieties with unknown potential. Not purchased but freely given out of respect, this tradition celebrates those who stood with Brokkr when others wouldn't, forming a sacred circle of trust that transcends the boundaries between realms.",
                    "image": "story-0011/PhoenixFlame.jpg",
                    "displayOrder": 11,
                    "hasAudio": true,
                    "isNew": true,
                    "downloadOptions": [
                        "fantasy",
                        "audio"
                    ]
                },
                "story-0012": {
                    "id": "story-0012",
                    "title": "The Forge Memory",
                    "sequence": "Part 12 of Brokkr's Saga",
                    "description": "As Brokkr's seedcraft grows increasingly complex, his traditional methods of documentation prove inadequate. When Eddan the chronicler brings him a mysterious \"memory tablet\" combining elven crystal-work with dwarven metallurgy, Brokkr reluctantly embraces this new tool. Through his struggles to adapt, he discovers that the tablet reveals hidden patterns in his phoenix seeds—connections that transform not just how he records his knowledge, but how he understands the very nature of his craft.",
                    "image": "story-0012/ForgeMemory.jpg",
                    "displayOrder": 12,
                    "hasAudio": true,
                    "isNew": true,
                    "downloadOptions": [
                        "fantasy",
                        "audio"
                    ]
                }
            }
        },
        "collection2": {
            "id": "collection2",
            "title": "Collection II: The Master's Art",
            "description": "Delve deeper into Brokkr's mastery as he combines his crafts in ways that blur the boundaries between creation, artistry, and magic itself.",
            "stories": {
                "story-2001": {
                    "id": "story-2001",
                    "title": "The Tattooed Seed",
                    "sequence": "Collection II - Part 1",
                    "description": "During his years in Muspelheim's prisons, Brokkr discovered more than just fire-craft—he found his gift for artistic creation. When he combines his newfound skills with his seedcraft mastery, the result is something unprecedented: seeds that carry not just genetic memory, but visual stories etched into their very shells. These living artworks become a new form of communication between realms, where each sprouting tells a tale.",
                    "image": "story-2001/TattooedSeed.jpg",
                    "displayOrder": 1,
                    "hasAudio": true,
                    "isNew": true,
                    "downloadOptions": [
                        "fantasy",
                        "audio"
                    ]
                },
                "story-2002": {
                    "id": "story-2002",
                    "title": "The Greenworld Envoys",
                    "sequence": "Collection II - Part 2",
                    "description": "When mysterious refugees from the distant world of Viridian Prime arrive through Heimdall's Rainbow Bridge, they bring with them a desperate plea and alien seeds that refuse to grow in foreign soil. Brokkr is called upon to help these Greenworld envoys establish sustainable agriculture to save their dying people. Through innovative fusion of dwarven seedcraft and alien bio-engineering, he creates the revolutionary \"Bridge Seeds\" - plants that remember their origin while embracing their new home. This collaboration not only saves the refugees but transforms Brokkr into an architect of inter-dimensional integration, eventually leading to the founding of the Council of Worlds.",
                    "image": "story-2002/GreenworldEnvoys.jpg",
                    "displayOrder": 2,
                    "hasAudio": true,
                    "isNew": true,
                    "downloadOptions": [
                        "fantasy",
                        "audio"
                    ]
                },
                "story-2003": {
                    "id": "story-2003",
                    "title": "The Divine Harvest Contest",
                    "sequence": "Collection II - Part 3",
                    "description": "When Asgard's sacred stores of sweetleaf herb run dangerously low, Odin calls for the Great Cultivation Contest - a legendary competition where master growers from across the Nine Realms compete to restock the gods' private reserves. Brokkr enters the contest not just to prove his seedcraft mastery, but to demonstrate that his hybrid techniques can produce varieties beyond anything the realms have seen. Facing off against Vanir nature-witches, Alfheim botanical experts, and mysterious competitors from distant corners of the cosmos, Brokkr must craft the perfect sweetleaf - one that carries not just potency, but the very essence of divine inspiration. The winner will earn the honor of becoming the official Royal Cultivator to the Aesir, and their strain will be preserved in Odin's personal garden for eternity.",
                    "image": "/stories/story-2003/DivineHarvestContest.jpg",
                    "displayOrder": 3,
                    "hasAudio": true,
                    "isNew": true,
                    "downloadOptions": [
                        "fantasy",
                        "audio"
                    ]
                },
                "story-2004": {
                    "id": "story-2004",
                    "title": "The Spore Awakening",
                    "sequence": "Collection II - Part 4",
                    "description": "When mysterious mushrooms spontaneously appear alongside Brokkr's seed containers after a humid morning, he discovers that some of his hybrid seeds carry unexpected spores. Seeking expertise, he visits his old friend Lonetree in Midgard, where they encounter the Mycelian Collective—a society that has built their entire civilization around mushroom cultivation and consumption. Under the guidance of ancient Oracles who commune through fungal networks, Brokkr learns that mushrooms represent an entirely unexplored frontier in his craft. Together with Lonetree, he develops revolutionary strains that catch the attention of the gods themselves, elevating mushrooms to the same sacred status as the divine sweetleaf and establishing a new chapter in inter-realm botanical mastery.",
                    "image": "story-2004/SporeAwakening.jpg",
                    "displayOrder": 4,
                    "hasAudio": true,
                    "isNew": true,
                    "downloadOptions": [
                        "fantasy",
                        "audio"
                    ]
                },
                "story-2005": {
                    "id": "story-2005",
                    "title": "The Knoppr-Haeli Partnership",
                    "sequence": "Collection II - Part 5",
                    "description": "When growing demands across the Nine Realms outpace available natural spaces, Brokkr receives word of an innovative craftsman in Svartalfheim who has developed revolutionary cultivation chambers called \"Knoppr-Haeli\" (Bud Bunkers). Seeking to expand cultivation possibilities beyond traditional gardens, Brokkr journeys to his homeland to meet Gambit, a non-grower whose engineering genius has created tents woven from enchanted threads and illuminated by crystal matrices. Together, they forge a partnership that revolutionizes how sweetleaf, fireweed, mushrooms, and medicinal herbs can be cultivated in controlled environments throughout the realms, opening new possibilities for growers operating in challenging conditions from Jotunheim's ice fields to Alfheim's crystal caves.",
                    "image": "story-2005/KnopprHaeliPartnership.jpg",
                    "displayOrder": 5,
                    "hasAudio": true,
                    "isNew": true,
                    "downloadOptions": [
                        "fantasy",
                        "audio"
                    ]
                },
                "story-2006": {
                    "id": "story-2006",
                    "title": "The Healing Grove",
                    "sequence": "Collection II - Part 6",
                    "description": "When Brokkr encounters Tóke, a former warrior who chose healing herbs over destructive battle-mead, he discovers a community of individuals seeking recovery through natural means. Facing prejudice from those who misunderstand their journey, Brokkr helps establish a sanctuary where his medicinal strains provide genuine healing and hope. Through Tóke's leadership and Brokkr's cultivation expertise, they create a place that proves that choosing wellness over oblivion is a sign of strength, not weakness - challenging ancient stigmas and opening minds to the true nature of recovery and renewal.",
                    "image": "story-2006/HealingGrove.jpg",
                    "displayOrder": 6,
                    "hasAudio": true,
                    "isNew": true,
                    "downloadOptions": [
                        "fantasy",
                        "audio"
                    ]
                },
                "story-2007": {
                    "id": "story-2007",
                    "title": "Athena's Wisdom: The Balance of Growth",
                    "sequence": "Collection II - Part 7",
                    "description": "When Brokkr and his fellow master growers face inconsistent harvests, they gather beneath Yggdrasil for a ceremony seeking guidance. Their offerings unexpectedly awaken Athena, a goddess of wisdom whose knowledge predates even Odin's. She reveals the ancient secrets of perfect balance in cultivation - how minerals, water, and light must exist in precise proportions to achieve optimal growth. Under her guidance, Brokkr creates revolutionary nutrient formulations that, when tested against traditional methods, produce harvests of unprecedented size and potency. As word of these balanced growing methods spreads, realms that once struggled with cultivation flourish, with even the most challenging environments yielding bountiful results when proper balance is achieved.",
                    "image": "story-2007/AthenasWisdom.jpg",
                    "displayOrder": 7,
                    "hasAudio": true,
                    "isNew": true,
                    "downloadOptions": [
                        "fantasy",
                        "audio"
                    ]
                }
            }
        }
    }
};

// Export for use in modules
if (typeof module !== 'undefined' && module.exports) {
    module.exports = storiesConfig;
}

// Make available globally
window.storiesConfig = storiesConfig;